### ISSUE TITLE
Demo crash when click ArekMicrophone

### ISSUE THREAD

**Issue by Huang-Libo** [ennioma/arek#47] opened 2016-12-18 06:47 UTC
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```
![2016-12-18 14 45 31](https://cloud.githubusercontent.com/assets/12227130/21292019/c374fd5a-c530-11e6-81be-a97c75d26235.png)

**Comment by ennioma** [comment] 2016-12-18 16:44
Hi @Huang-Libo,
I'm not able to reproduce this.

Could you please provice me more details?

**Comment by Huang-Libo** [comment] 2016-12-18 17:16
I run the demo on iPhone7 Plus(not simulator), iOS 10.2

**Comment by ennioma** [comment] 2016-12-18 17:39
Ok thanks,
I'll take a look as soon as possible!

**Comment by evermeer** [comment] 2016-12-19 15:04
Isn't this fixed with https://github.com/ennioma/arek/commit/a5b073d74c3486a13918f7101fba0b54280942dd

**Comment by ennioma** [comment] 2016-12-19 15:05
Yes @evermeer, it should but In the meanwhile I'd test it on a device.

**Comment by ennioma** [comment] 2016-12-21 22:20
This should be fixed @Huang-Libo

**Closed by ennioma** 2016-12-21 22:20 UTC

**Comment by gerchicov-bp** [comment] 2016-12-29 16:19
still appears

**Comment by evermeer** [comment] 2016-12-30 10:06
NSMicrophoneUsageDescription is missing again from the demo

**Comment by ennioma** [comment] 2016-12-30 22:34
Should be definitely closed with #71
